language: python
os:
  - linux
  - osx
python:
    - "2.7"
before_script: pip install coveralls
script:
    - "py.test"
    - "coverage run --source=dayu_path setup.py test"
after_success:
    - coveralls
